# Generated by Django 5.0.2 on 2024-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooduser', '0002_commensettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotprofile',
            name='paymentsts',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hotprofile',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
