# Generated by Django 5.0.2 on 2024-03-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooduser', '0003_hotprofile_paymentsts_hotprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cattxt',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
