# Generated by Django 5.0.2 on 2024-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooduser', '0004_items_cattxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='catsts',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
