# Generated by Django 5.0.2 on 2024-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooduser', '0005_categorys_catsts'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgtoadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=250, null=True)),
                ('dates', models.CharField(max_length=250, null=True)),
                ('msg', models.CharField(max_length=250, null=True)),
                ('sts', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='msgtostore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=250, null=True)),
                ('dates', models.CharField(max_length=250, null=True)),
                ('msg', models.CharField(max_length=250, null=True)),
                ('sts', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
